create table SALARIES(
ID NUMBER (*,0) NOT NULL,
EMPLOYEE_ID NUMBER (*,0) NOT NULL,
PROJECT_ID NUMBER (*,0),
SALARY NUMBER (10,2) NOT NULL
)
CREATE TABLE PROJECTS(
ID NUMBER (*,0) NOT NULL,
CODE VARCHAR2 (255 BYTE) NOT NULL,
MANAGER_ID NUMBER (*,0),
BUDGET NUMBER (10,2) NOT NULL,
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE
)
CREATE TABLE EMPLOYEES(
ID NUMBER (*,0),
MANAGER_ID NUMBER (*,0),
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR2 (255 BYTE) NOT NULL
)
ALTER TABLE SALARIES ADD CONSTRAINT SALARIES_PK PRIMARY KEY (ID);
ALTER TABLE PROJECTS ADD CONSTRAINT PROJECTS_PK PRIMARY KEY (ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID);

ALTER TABLE SALARIES ADD CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID);
ALTER TABLE SALARIES ADD CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID);
ALTER TABLE PROJECTS ADD CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (ID);


--1. Write a SQL query to fetch project code and count of employees (code, employees_count) sorted by employees_count in descending order. example 48205501099, 4
SELECT COUNT(MANAGER_ID),CODE FROM PROJECTS
GROUP BY MANAGER_ID,CODE
ORDER BY MANAGER_ID DESC;


--  -2. Write a query to fetch employee names of those who are not assigned to any project

SELECT NAME
FROM EMPLOYEES
LEFT JOIN EMPLOYEES  ON PROJECTS = EMPLOYEES
WHERE PROYEES IS NULL
 
----3. Write a SQL query to fetch all the Employees who are also managers from employees table

SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL;

---- 4.Write a SQL query to fetch each employee with the name of his/her boss in one column named "employee_boss" separated by ' - ' 
-- (don't forget the spaces). Example: "Drew Rosario - Holmes Manning", "Emery Kelley - Holmes Manning" (employee name - manager name)

SELECT CONCAT(CONCAT(employees1_.FULL_NAME,' - '),employees2_.FULL_NAME) AS employee_boss
FROM EMPLOYEES employees1_
INNER JOIN EMPLOYEES employees2_ ON employees1_.MANAGER_ID = employees2_.ID; 

---5. Write a SQL query to fetch all the employees which first name is Kermit

SELECT * FROM EMPLOYEES
WHERE FULL_NAME LIKE 'kermit';







